import type { ResearchResponse } from "@/types/report";

export const MOCK_RESEARCH: ResearchResponse = {
  products: [
    {
      title: "MSHUKCOE Wireless Headphones In-ear Design Noise Cancelling True Wireless Earbuds",
      price: 14.9,
      sold_count: "33.8K sold",
      rating: 4.2,
      image_url: "",
      product_url: "",
      shop_name: "MSHUKCOE",
      data_source: "seed",
    },
    {
      title: "JLab GO Sport+ True Wireless Earbuds with Charging Case",
      price: 24.98,
      sold_count: "49.5K sold",
      rating: 4.5,
      image_url: "",
      product_url: "",
      shop_name: "JLab",
      data_source: "seed",
    },
    {
      title: "Nothing Ear (a) Wireless Earbuds with ChatGPT Integration",
      price: 59.99,
      sold_count: "518 sold",
      rating: 4.3,
      image_url: "",
      product_url: "",
      shop_name: "CMF by Nothing",
      data_source: "seed",
    },
    {
      title: "Wireless Bluetooth Headphones Tiny Size Invisible Earbuds (2 Pairs)",
      price: 13.99,
      sold_count: "931 sold",
      rating: 3.9,
      image_url: "",
      product_url: "",
      shop_name: "Example Seller",
      data_source: "seed",
    },
    {
      title: "CMF Buds 2a Wireless Bluetooth Earbuds",
      price: 39.99,
      sold_count: "2.1K sold",
      rating: 4.6,
      image_url: "",
      product_url: "",
      shop_name: "CMF by Nothing",
      data_source: "seed",
    },
  ],
  analysis: {
    product: {
      title: "MSHUKCOE Wireless Headphones In-ear Noise Cancelling True Wireless Earbuds",
      price: "$14.90",
      sold_count: "33.8K sold",
      rating: 4.2,
      image_url: "",
      shop_name: "MSHUKCOE",
    },
    opportunity_score: 70,
    market_size: { en: "Large", zh: "大" },
    competition: { en: "Medium", zh: "中" },
    growth_trend: { en: "+15% vs last month", zh: "+15% 环比增长" },
    is_estimated: true,
    selling_points: [
      { en: "Active noise cancelling at entry-level price point", zh: "入门级价格的主动降噪功能" },
      { en: "In-ear design with ergonomic fit for extended wear", zh: "符合人体工学的入耳式设计，适合长时间佩戴" },
      { en: "True wireless with stable Bluetooth 6.0 connectivity", zh: "真无线设计，蓝牙6.0稳定连接" },
      { en: "Waterproof rating suitable for workouts and outdoor use", zh: "防水等级适合运动和户外使用" },
    ],
    pain_points: [
      { en: "Low brand recognition in a crowded category", zh: "在竞争激烈的品类中品牌知名度低" },
      { en: "No rating data available — buyers may hesitate", zh: "缺少评分数据，买家可能犹豫" },
      { en: "Average battery life compared to premium alternatives", zh: "与高端竞品相比续航表现一般" },
      { en: "Limited color and style options for personalization", zh: "颜色和款式选择有限" },
    ],
    differentiation_opportunities: [
      { en: "Add longer battery life (40h+) as a headline feature", zh: "主打40小时以上超长续航" },
      { en: "Include IPX6 waterproof certification in packaging", zh: "在包装上标注IPX6防水认证" },
      { en: "Offer 3+ colorways with matching case designs", zh: "提供3种以上配色及配套充电盒设计" },
      { en: "Bundle with a 1-year warranty to reduce purchase friction", zh: "附赠1年质保，降低购买顾虑" },
    ],
  },
  strategy: {
    target_audience: {
      en: "Budget-conscious young adults aged 18–30, students and commuters seeking affordable noise-cancelling earbuds for daily use",
      zh: "18-30岁注重性价比的年轻群体，包括学生和通勤族，寻求日常使用的平价降噪耳机",
    },
    content_ideas: [
      { en: "Unboxing video highlighting premium feel at a budget price", zh: "开箱视频：展示平价价位的高级质感" },
      { en: "Side-by-side noise cancelling test vs. $100+ earbuds", zh: "横向对比：与$100+耳机的降噪效果实测" },
      { en: "Day-in-the-life: commute, gym, study sessions with the earbuds", zh: "日常vlog：通勤、健身、学习全场景使用体验" },
      { en: "User testimonial compilation — real reviews, real reactions", zh: "用户真实评价合集" },
    ],
    influencer_types: [
      { en: "Budget tech reviewers", zh: "性价比数码测评博主" },
      { en: "College lifestyle creators", zh: "大学生活方式博主" },
      { en: "Fitness & workout influencers", zh: "健身运动博主" },
    ],
    pricing_suggestion: {
      en: "$14.90 – $24.90",
      zh: "$14.90 – $24.90",
    },
    risk_analysis: {
      en: "Primary risk is low brand trust in a category dominated by established names; price wars could compress already-thin margins. Recommend aggressive content marketing to build credibility quickly.",
      zh: "主要风险是在成熟品牌主导的品类中品牌信任度低；价格战可能进一步压缩利润空间。建议通过积极的内容营销快速建立信任。",
    },
    recommendation: {
      status: "recommended" as const,
      reason: {
        en: "Strong market demand with moderate competition; low-price strategy enables rapid scaling",
        zh: "Strong market demand with moderate competition; entry-level pricing enables fast growth",
      },
    },
  },
  listing: {
    seo_title: { en: "Best Wireless Earbuds — Active Noise Cancelling", zh: "Best Wireless Earbuds — Active Noise Cancelling" },
    bullets: [
      { en: "Active noise cancelling for immersive sound", zh: "Active noise cancellation for immersive audio" },
      { en: "40-hour battery with USB-C quick charge", zh: "40-hour battery life with USB-C fast charging" },
      { en: "IPX6 waterproof for workouts and rain", zh: "IPX6 waterproof rating for sports and outdoor use" },
      { en: "Bluetooth 6.0 with dual-device pairing", zh: "Bluetooth 6.0 with dual-device connection" },
      { en: "Ergonomic fit with 3 ear-tip sizes included", zh: "Ergonomic design with 3 sizes of ear tips" },
    ],
    description: {
      en: "Premium sound at an accessible price. These wireless earbuds combine active noise cancelling, waterproofing, and all-day comfort. Perfect for commutes, workouts, and calls.",
      zh: "Premium sound quality at an affordable price. Combines active noise cancellation, waterproofing, and all-day comfort. Ideal for commuting, exercise, and calls.",
    },
    backend_keywords: ["wireless earbuds", "noise cancelling", "bluetooth", "waterproof", "tiktok shop", "best seller"],
  },
};
